# Generated by Django 5.0.3 on 2024-06-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mytask",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
