# Generated by Django 5.0.3 on 2024-06-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_mytask_is_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="is_important",
            field=models.BooleanField(default=False),
        ),
    ]
